-- Base classes
import 'classes/baseClasses/GameObject'
import 'classes/baseClasses/Enemy'
import 'classes/baseClasses/Obstacle'
import 'classes/baseClasses/Boost'
import 'classes/baseClasses/Dressings'

-- Objects
import 'classes/objects/Bueiro'
import 'classes/objects/Pastel'
import 'classes/objects/Oil'
import 'classes/objects/Bola'
import 'classes/objects/Pipoqueiro'
import 'classes/objects/Uninho'
import 'classes/objects/Motoboy'
import 'classes/objects/Player'

-- Background objects
import 'classes/background/Poste'
import 'classes/background/Placa'
import 'classes/background/Partida'
import 'classes/background/Bandeirinhas'
import 'classes/background/Bandeirinhas02'
import 'classes/background/BrFlag'
import 'classes/background/CaFlag'
import 'classes/background/Fios'
import 'classes/background/Fitinhas'
import 'classes/background/Hexa'
import 'classes/background/Placa02'
import 'classes/background/PosteQuebrado'
import 'classes/background/Powercable'
import 'classes/background/ScFlag'
import 'classes/background/Worldcup'
import 'classes/background/curbL'
import 'classes/background/curbR'
import 'classes/background/Finish'